### ISSUE TITLE
How Vue-specific is this?

### ISSUE THREAD

**Issue by dgp-web** [retejs/minimap-plugin#29]
Hello folks,

We installed this plugin and got it to work easily. However, we noticed that it has a fix dependency to "vue".

This leads to us pulling in Vue for an our Angular app by accident which can cause unwanted side effects - as already testified by the following warning when running unit tests.

```
Chrome Headless 109.0.5414.76 (Windows 10) INFO LOG: 'Download the Vue Devtools extension for a better development experience: https://github.com/vuejs/vue-devtools'
Chrome Headless 109.0.5414.76 (Windows 10) INFO LOG: 'You are running Vue in development mode.  Make sure to turn on production mode when deploying for production. See more tips at https://vuejs.org/guide/deployment.html'
```

That feels off somehow. Do you need this fix npm dependency for the minimap-plugin?

Best,
dgp-web

**Comment by Ni55aN** [comment]
Minimap (for Rete.js v1) is completely based on Vue.js

**Comment by dgp-web** [comment]
Thanks for your feedback!

Would it be possible to serve the Plugin content so it doesn't include this hard dependency?

I didn't have a look at your code but maybe components could be served as web components (https://vuejs.org/guide/extras/web-components.html#building-custom-elements-with-vue)?

I know from my Angular that experience that this approach includes a tiny version of the framework in the code and this should remove the need of an npm dependency.

It would also come with the benefit of making this awesome plugin more accessible to non-Vue projects.

Maybe we could provide some help if needed.

**Comment by Ni55aN** [comment]
Using Vue.js components as web components also requires 'vue' dependency.

If you mean the ability to switch between different rendering plugin (for Vue, React or Angular), then it will be supported in v2
