### ISSUE TITLE
Customize minimap colors

### ISSUE THREAD

**Issue by gripzyyy** [retejs/minimap-plugin#37]
Is there any way to customize the minimap colors?
I see there are some random css classes generated for the minimap colors, but in your source code I can't find any styled components or something that would indicate how the styling is done.
There is no guide for this as far as I can see.

**Comment by Ni55aN** [comment]
> some random css classes generated

yes, this is how it works for react rendering plugin

https://github.com/retejs/react-plugin/blob/main/src/presets/minimap/components/Minimap.tsx#L11

The recommended approach for customizing minimap (so far, compared classic preset or context menu) is copying [the preset](https://github.com/retejs/react-plugin/blob/main/src/presets/minimap) and customize it to your needs
